### PR TITLE
ADDON-37163: Migrate to new UCC UI

### PR DESCRIPTION
**Pull request by harshpatel-crest**
Jira: https://jira.splunk.com/browse/ADDON-37163

Changes:

- Migrated to new UCC UI

### CODE REVIEW

**Review by dhruvanshus-crest — APPROVED** [review]

**Review by pdudhaiya-crest — APPROVED** [review]

**Comment by harshpatel-crest** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by arys-splunk — APPROVED** [review]

**Comment by arys-splunk** [comment]
@harshpatel-crest what do you think about merging it? so we are in sync with ucc-generator release.

**Comment by harshpatel-crest** [comment]
@arys-splunk Yes, going to merge now. After this SmartX also needs to be updated to pass UI tests. Will do it in separate PR.

**Pull request merged**
